---
title: "Informe Ventana Atencional"
author: "Anibal de Paul"
date: "13 de mayo de 2020"
#bibliography: Elementos exportados.bib
output: ioslides_presentation

---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
library(tidyverse)
library(R.matlab)
library(readr)
library(reshape2)
library(plyr)
#Cargo el workspace
load("C:/Users/Anibal/Documents/R/attentional-window/procesamientoVA.RData")

```

## Efectos de entrenamiento con MOT en Ventana Atencional
En esta expriencia utilizamos el paradigma MOT (seguimiento de objetos mútiples o "Multiple Object Tracking") como herramienta de entrenamiento atencional. 

## Slide with Bullets

- Bullet 1
- Bullet 2
- Bullet 3

## Slide with R Output

```{r , echo = FALSE, fig.width = 8, fig.asp = 0.63}
ggplot(data = df_porcentaje, aes(x= Ntrials , y= TRialOK)) + geom_point(aes(color = Condicion), alpha = 0.5) +  geom_text(aes( x= 1, y = 100, label = "Referencia", hjust = -0.2), size = 3) +
  facet_wrap( ~ Observador, scales="free_x")



```

## Slide with Plot

```{r pressure}
plot(pressure)
```

## References
